export const NAME = 'CrossCompute';
export const NAMESPACE = 'crosscompute';
export const COMMAND_PALETTE_CATEGORY = NAMESPACE;
export const RUN_AUTOMATION_COMMAND =
  COMMAND_PALETTE_CATEGORY + ':RunAutomation';
export const TOOLBAR_BUTTON_INDEX = 10;
export const RUN_AUTOMATION_BUTTON_TIMEOUT_IN_MILLISECONDS = 10000;
export const RUN_AUTOMATION_POLLING_INTERVAL_IN_MILLISECONDS = 3000;
